name: wedplan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.1
  permission_handler: ^11.3.1
  json_serializable: ^6.9.0
  get_it: ^8.0.3
  bloc: ^8.1.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.14
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/MontserratAlternates-Bold.ttf  
    
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf  
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700